# Generated by Django 4.2 on 2024-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=500)),
                ('facility_type', models.CharField(max_length=50)),
                ('location_description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=255)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
